### ISSUE TITLE
main build broken: `HostTensorShell.strides` type mismatch after tt-mlir uplift #4957

### ISSUE THREAD

**Issue by kmabeeTT** [tenstorrent/tt-xla#5155]
### Problem
`origin/main` does not compile. Two `TTPJRTApi` sources fail to build against the pinned tt-mlir (`464a5f3`):

```
buffer_instance.cc:260: error: no viable conversion from 'vector<int64_t>' to 'vector<uint32_t>'
flatbuffer_loaded_executable_instance.cc:122: error: no matching function for call to 'createOwnedHostTensor'
```

### Root cause
Semantic merge conflict between two independently-landed PRs:

- **#4617** (James Xu) introduced `HostTensorShell` with `std::vector<std::uint32_t> strides` (`tensor.h:57`) and a `createOwnedHostTensor(..., shell->strides, ...)` call (`flatbuffer_loaded_executable_instance.cc:123`), written against the then-pinned tt-mlir (`c5f3984`) where the stride param was `uint32`.
- **#4957** (Vladimir Milosevic) uplifted tt-mlir to `464a5f3`, which changed `createOwnedHostTensor`'s stride param `uint32 -> int64`. The uplift updated `buffer_instance.cc` (local `strides` vars and `calculateStrides()` -> `int64`) but did **not** update `HostTensorShell.strides` in `tensor.h`.

Result, `HostTensorShell.strides` (`uint32`) is now wrong in both directions:
- `buffer_instance.cc:260` stores the `int64` local `strides` into the `uint32` struct field.
- `flatbuffer:123` passes the `uint32` `shell->strides` into the now-`int64` `createOwnedHostTensor`.

#4957's CI ran before #4617 merged, so the call site was never compiled against the new signature.

### Suggested fix
One line, `pjrt_implementation/inc/api/tensor.h:57`:

```cpp
-    std::vector<std::uint32_t> strides;
+    std::vector<std::int64_t> strides;
```

This makes it consistent end-to-end: `buffer_instance.cc:225` already computes `strides` as `int64`, and the new `createOwnedHostTensor` expects `int64`. `shape` stays `uint32` (that param was unchanged). `HostTensorShell.strides` has only the one consumer, so nothing else needs touching.

### Owner
@jameszianxuTT  (owns `HostTensorShell` / #4617); cc @acicovicTT (awareness for #4957 uplift surfaced it).
