### ISSUE TITLE
models failing in nightly with  TypeError and torch._dynamo.exc.TorchRuntimeError

### ISSUE THREAD

**Issue by ctr-pmuruganTT** [tenstorrent/tt-xla#2396]
Few models failed in [nightly](https://github.com/tenstorrent/tt-xla/actions/runs/19842210049/attempts/1) 

```
tests/runner/test_models.py::test_all_models_torch[phi3/causal_lm/pytorch-microsoft/Phi-3-mini-4k-instruct-single_device-full-inference]

tests/runner/test_models.py::test_all_models_torch[phi3/causal_lm/pytorch-microsoft/Phi-3-mini-128k-instruct-single_device-full-inference]

tests/runner/test_models.py::test_all_models_torch[arnold/pytorch-vizdoom_2017_track2_rnn-single_device-full-inference]

tests/runner/test_models.py::test_all_models_torch[arnold/pytorch-vizdoom_2017_track1_rnn-single_device-full-inference]

tests/runner/test_models.py::test_all_models_torch[arnold/pytorch-deathmatch_shotgun_rnn-single_device-full-inference]

tests/runner/test_models.py::test_all_models_torch[transfuser/pytorch-single_device-full-inference] 
```

The above models failed with the error as follows

```
TypeError: arange() received an invalid combination of arguments - got (int, int, device=torch.Size, dtype=torch.dtype), but expected one of:
E            * (Number end, *, Tensor out = None, torch.dtype dtype = None, torch.layout layout = None, torch.device device = None, bool pin_memory = False, bool requires_grad = False)
E            * (Number start, Number end, *, torch.dtype dtype = None, torch.layout layout = None, torch.device device = None, bool pin_memory = False, bool requires_grad = False)
E            * (Number start, Number end, Number step = 1, *, Tensor out = None, torch.dtype dtype = None, torch.layout layout = None, torch.device device = None, bool pin_memory = False, bool requires_grad = False)
```

`tests/runner/test_models.py::test_all_models_torch[transfuser/pytorch-single_device-full-inference] ` model failed with 

```
 torch._dynamo.exc.TorchRuntimeError: Dynamo failed to run FX node with fake tensors: call_function <Wrapped method <original div>>(*(FakeTensor(..., size=()), 2), **{}): got AttributeError("'ndarray' object has no attribute 'div'")
E       
E       from user code:
E          File "/__w/tt-xla/tt-xla/third_party/tt_forge_models/transfuser/pytorch/src/model.py", line 389, in forward
E           bbox = self.get_bbox_local_metric(bbox)
E         File "/__w/tt-xla/tt-xla/third_party/tt_forge_models/transfuser/pytorch/src/model.py", line 400, in get_bbox_local_metric
E           w = w / 2 / 8
E         File "/__w/tt-xla/tt-xla/venv/lib/python3.11/site-packages/tt_torch/torch_overrides.py", line 18, in __torch_function__
E           return func(*args, **(kwargs or {}))
E       
E       Set TORCHDYNAMO_VERBOSE=1 for the internal stack trace (please do this especially if you're reporting a bug to PyTorch). For even more developer context, set TORCH_LOGS="+dynamo"
```

Investigate the reason for these failures

**Comment by ctr-pmuruganTT** [comment]
When bisected these failures, it is found that 4833d7812869a36fc6be92f797a43256b95793dd is responsible for the failures.

tested the models in CI with this commit and its previous commit

With commit 32791d42af8819deb20c1af7642d4c027a0b80a0 : https://github.com/tenstorrent/tt-xla/actions/runs/19849572780 It is passing
With commit 4833d7812869a36fc6be92f797a43256b95793dd : https://github.com/tenstorrent/tt-xla/actions/runs/19849559381 It is failing

**Comment by ajakovljevicTT** [comment]
Since both phi models and transfuser are RED, marking this issue as P0 and tagging @AleksKnezevic as the author of commit to triage. Let me know if someone else is more suited to this.

**Comment by gengelageTT** [comment]
Update:
Trying to debug `pytest -svv tests/runner/test_models.py::test_all_models_torch[phi3/causal_lm/pytorch-microsoft/Phi-3-mini-4k-instruct-single_device-full-inference]`

Placed a breakpoint [here](https://huggingface.co/microsoft/Phi-3-mini-4k-instruct/blob/main/modeling_phi3.py#L1032), and when torch_function_override is enabled, I see the following behaviour:
```
-> breakpoint()
(Pdb) input_ids.shape
torch.Size([1, 256])
(Pdb) input_ids.device
torch.Size([1, 256])
```
```
-> breakpoint()
(Pdb) input_ids.device
device(type='cpu')
(Pdb) input_ids.shape
device(type='cpu')
(Pdb) input_ids.name
device(type='cpu')
```
It seems that whichever attribute is called first is what will be returned for any proceeding attribute calls. Since `input_ids.shape` is called before `input_ids.device`, when `input_ids.device is called its returning `input_ids.shape` instead.

When TorchFunctionOverride is reduced to 
```
class TorchFunctionOverride(TorchFunctionMode):
        return func(*args, **(kwargs or {}))
```
the test passes, so the issue is in the logic for linear and matmul functions.

However, when I add a breakpoint after
```
if not torch.compiler.is_compiling() and (
     func.__name__ == "matmul" or func.__name__ == "linear"
):
```
it's never reached, which means the issue is likely in the calls made in the if statement itself.

**Comment by gengelageTT** [comment]
`tests/runner/test_models.py::test_all_models_torch[transfuser/pytorch-single_device-full-inference]` is failing because `func(*args, **(kwargs or {}))` is calling torch methods on numpy arrays which can lead to errors like:
```
AttributeError: 'ndarray' object has no attribute 'div_'
```
It seems that when torch.compile/dynamo traces operations on numpy arrays, it wraps them with torch's fake tensor machinery. The override being active causes dynamo to treat numpy operations as torch operations in some cases. 

To fix this we can use the default numpy handlers instead of returning a torch_overide function for any function with `np.array` args:
```
# Return NotImplemented to use the default numpy handlers instead
        if args:
            for arg in args:
                if isinstance(arg, np.ndarray):
                    return NotImplemented
```

Since `linear` and `matmul` shouldn't have `ndarray` inputs there should be no issues with using the default numpy handlers any time there's a `ndarray` input.

I'll make a pr with these fixes shortly

**Comment by gengelageTT** [comment]
After rebasing to latest main, transfuser is failing with [a new error](https://github.com/tenstorrent/tt-xla/actions/runs/19971194084/job/57276787750#step:17:266):
```
>           if acc.type == "jax":
               ^^^^^^^^
E           torch._dynamo.exc.BackendCompilerFailed: backend='inductor' raised:
E           AttributeError: 'NoneType' object has no attribute 'type'
```
This is not present when the torch override is disabled so it's another TorchFunctionOverride issue.

I removed the fixes and unit tests for transfuser from[ this pr](https://github.com/tenstorrent/tt-xla/pull/2452) and merged it, so all affected tests but transfuser should now be passing.


Further findings:
Trying to only return `NotImplemented` for failing functions (`div` and `mul_`) results in a transfuser "passing" but hitting the recompile limit:
```
W1205 22:25:57.934000 571415 torch/_dynamo/convert_frame.py:964] [1/8] torch._dynamo hit config.recompile_limit (8)
W1205 22:25:57.934000 571415 torch/_dynamo/convert_frame.py:964] [1/8]    function: '__torch_function__' (/localdev/gengelage/tt-xla/python_package/tt_torch/torch_overrides.py:10)
W1205 22:25:57.934000 571415 torch/_dynamo/convert_frame.py:964] [1/8]    last reason: 1/7: ___check_type_id(args[0], 9692864)                     
W1205 22:25:57.934000 571415 torch/_dynamo/convert_frame.py:964] [1/8] To log all recompilation reasons, use TORCH_LOGS="recompiles".
W1205 22:25:57.934000 571415 torch/_dynamo/convert_frame.py:964] [1/8] To diagnose recompilation issues, see https://pytorch.org/docs/main/torch.compiler_troubleshooting.html.
```
