### ISSUE TITLE
[Investigation] Reconsider manylinux build flags added during June 26 uplifts

### ISSUE THREAD

**Issue by acicovicTT** [tenstorrent/tt-xla#5275]
Two build flags have been recently added to push through manylinux builds during uplifts/serious nightly failures that should be reconsidered. Maybe it's cleaner to remove them and replace them with something else that is a better long term solution - this issue is used for tracking this investigation:

1. Compiler flag in `third_party/CMakeLists.txt`:
```
-DCMAKE_CXX_FLAGS=-Wno-error=pass-failed # Uplift hack, manylinux build threw because stablehlo autogenerated source had a failed loop unroll.s
```
  - No original issue, but it was an obvious compilation error in the new version of the compiler.

2. Linker flag `--no-rosegment` in `.github/workflows/call-build-manylinux.yml` (added in https://github.com/tenstorrent/tt-xla/pull/5181):
```
LDFLAGS="-Wl,--no-rosegment"
```
  - Original issue: https://github.com/tenstorrent/tt-xla/issues/5172

**Comment by acicovicTT** [comment]
## Investigation: `-Wno-error=pass-failed` (part 1) — **cannot be removed**

Tested removal in #5408. The manylinux CI build **fails**:

```
build/stablehlo/stablehlo/dialect/StablehloOps.cpp.inc:322:30: error: loop not unrolled:
the optimizer was unable to perform the requested transformation ...
[-Werror,-Wpass-failed=transform-warning]
```
(also lines 437, 447, 589, …)

### Root cause
tt-mlir compiles StableHLO's sources **in-tree** (`add_subdirectory` of the toolchain checkout) under its global `-Werror` (tt-mlir `CMakeLists.txt:108`). The tablegen-generated `StablehloOps.cpp.inc` contains loop-unroll metadata that the optimizer cannot honor in a Release build → Clang emits `-Wpass-failed=transform-warning` → `-Werror` promotes it to a hard error. `-Wno-error=pass-failed` demotes just that one diagnostic.

### Why it still fires (key finding)
The **manylinux image compiles with Clang 21.1.8**, not the clang-20 used by the regular CI ubuntu image. I verified locally that **clang 20.1.8 unrolls these loops fine** — a standalone Release build of the current StableHLO sources (same pin) with `-Werror=pass-failed` is completely clean. So this is a **clang-21-specific** unroller regression, not something we changed.

The StableHLO/LLVM pins have been unchanged since the Nov 2025 uplift, so nothing on our side will make this go away.

### Conclusion
The flag is still required and minimal (it demotes only `pass-failed`, which is a non-fatal "optimizer couldn't unroll" remark — generated code is still correct). It can be revisited once clang's loop unroller or the upstream StableHLO tablegen output changes. Closing #5408.
